# Generated by Django 3.1.3 on 2021-03-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='spo2',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=98.5, max_digits=5),
            preserve_default=False,
        ),
    ]
