# Generated by Django 3.1.3 on 2021-03-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0003_auto_20210324_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='spo2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='temperature',
        ),
    ]
