# Generated by Django 3.1.3 on 2021-04-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0006_auto_20210425_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='force_vital_capacity',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='peak_expiratory_flow',
        ),
        migrations.AddField(
            model_name='patient',
            name='bp',
            field=models.IntegerField(default=120, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='fvc',
            field=models.DecimalField(decimal_places=2, default=3.9, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='pef',
            field=models.IntegerField(default=500, max_length=9),
            preserve_default=False,
        ),
    ]
