# Generated by Django 3.1.3 on 2021-05-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0007_auto_20210428_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fev1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fvc',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pef',
        ),
        migrations.AddField(
            model_name='patient',
            name='airQuality',
            field=models.CharField(default=54, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='ecg',
            field=models.IntegerField(default=45, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='heartRate',
            field=models.CharField(default=16, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='humidity',
            field=models.DecimalField(decimal_places=2, default=45, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='roomTemp',
            field=models.DecimalField(decimal_places=2, default=48, max_digits=4),
            preserve_default=False,
        ),
    ]
