# Generated by Django 3.1.4 on 2021-02-12 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DOCTOR', '0001_initial'),
        ('PATIENT', '0001_initial'),
        ('COMMON_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCTOR.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient'),
        ),
    ]
