# Generated by Django 3.1.3 on 2021-01-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsthmaTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
