# Generated by Django 3.1.3 on 2021-01-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsthmaTracker', '0002_auto_20210102_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
