# Generated by Django 3.1.3 on 2021-01-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsthmaTracker', '0003_auto_20210103_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
