# Generated by Django 3.1.3 on 2021-01-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsthmaTracker', '0004_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(max_length=13),
        ),
    ]
