# Generated by Django 3.1.3 on 2021-01-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsthmaTracker', '0005_auto_20210103_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
