# Generated by Django 3.1.3 on 2021-05-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bmdc_no',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
